controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

## match /first
first_page:
    path: /first
    controller: App\Controller\FirstController::index

## matches /article/en/2010/my-post
article:
    path: /article/{_locale}/{year}/{slug}.{_format}
    controller: App\Controller\ArticleController::index
    defaults: 
        _format: html
    requirements: 
        _locale: en|fr
        _format: html|rss
        year: \d+

routing_distributed_v1:
    resource: '../src/Resources/config/routing.yaml'
    type: yaml


# to_google:
to_google:
    path: /to-google
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults: 
        path: 'https://google.es'
        permanent: true