doctrine:
    dbal:
        default_connection: default
        connections:
            default: 
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            customer: 
                url: '%env(resolve:DATABASE_URL_CUSTOMER)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
        # url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        entity_managers:
            default: 
                connection: default
                mappings: 
                    Main:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            customer:
                connection: customer
                mappings: 
                    Customer:                
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Customer'
                        prefix: 'App\Entity\Customer'
                        alias: Customer      

