services:
    app.login_lister:
      class: App\EventListener\LoginListener
      arguments: ['@doctrine.orm.entity_manager']
      tags:
          - { name: 'kernel.event_listener', event: 'security.interactive_login' }          